Update weather-data.yml
- Added debugging section (received error when downloading this morning)

diff --git a/.github/workflows/weather-data.yml b/.github/workflows/weather-data.yml
--- a/.github/workflows/weather-data.yml
+++ b/.github/workflows/weather-data.yml
@@ -18,17 +18,25 @@ jobs:
         uses: actions/checkout@v3
         with: 
           persist-credentials: true  # ensures credentials are available for pushing changes
-      
-      - name: Install wget
-        run: sudo apt-get install -y wget
 
-      # Step three: run the script
+      # Step two: verify tools (optional but helps with debugging) 
+      - name: Varify required tools 
+        run: |
+          which date || echo "date command missing"
+          which touch || echo "touch command missing"
+          which wget || echo "wget command missing" 
+
+      #Step three:               
+      - name: Install wget
+        run: sudo apt-get update && sudo apt -get install -y wget
+
+      # Step four: run the script
       - name: Run weather.sh script
         run: |
           chmod +x weather.sh
           ./weather.sh
 
-      # Step three: commit and push changes back to repository 
+      # Step five: commit and push changes back to repository 
       - name: Commit and push changes
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
